### ISSUE TITLE
Glossy Autocomplete

### ISSUE THREAD

**Issue by szymonmasternak** [swaits/typst-collection#3]
Is it possible to get autocomplete on glossy when typing a glossary term?

Right now when using glossarium package, I can see an autocomplete preview for all possible glossary terms.
![image](https://github.com/user-attachments/assets/2b893b90-2100-4bc7-9e6c-38572f451b6f)

On glossy the only thing I see is this:
![image](https://github.com/user-attachments/assets/471ee04c-4766-42c9-9d65-fb4db06fbf11)

I think it would be a nice feature to implement.

Thanks
Szymon.

**Comment by swaits** [comment]
Interesting. I'll take a look and see if I can understand why this works in `glossarium`.

**Comment by swaits** [comment]
After thinking about it a bit I realized that it is working just the same as `glossarium`. However, the reason you're not seeing the same things on auto-complete is because `glossy` takes a different approach to labeling and referencing.

Each time you use a term, it gets a label like `__gloss:css.0`, `__gloss:css.1`, and so on. These labels are referenced later in the index, so the page numbers listed for a term can link back to the right usage.

I have an idea about something that might not really fix your autocomplete issue, but might improve the usability dramatically. I'll experiment with it in the coming days.

**Comment by swaits** [comment]
Although, thinking on it further, each time you use a term, like `@css`, that should also get added via your LSP, and since `@` sorts before `_` should get listed first in your autocompletion. So, I'm stumped. I'll keep thinking about it.

**Comment by eltos** [comment]
The glossarium package requires users to have a glossary list, and in there creates labels for each entry, which the typst autocomplete function can pick up. It also creates clickable links to the glossary list, which is useful, but imposes the limitation that you cannot use glossarium without actually printing the glossary list.

Glossy on the other hand uses a show rule to hook into the reference macro and can be used even if you don't want to print the glossary list.

Some ideas:

- A simple idea (at least for the case where a glossary list is actually shown via `#glossary()`) would be to change the label used during the glossary list creation in https://github.com/swaits/typst-collection/blob/f4b7cc1374a6a32ac61b051dfaeb503e4d456cfa/glossy/src/gloss.typ#L425
to use `label(key)` instead of `__dict_label(key)` to get `@css` instead of `@__gloss:css`. I think the label is currently not used, but if at some point you want to use it e.g. to create links to the glossary list, then it could be useful to add `label(key)` as an additional key instead of replacing it

- Another idea (also for the case where a glossary list is not used) would be to make `__term_label(key, index)` here
https://github.com/swaits/typst-collection/blob/f4b7cc1374a6a32ac61b051dfaeb503e4d456cfa/glossy/src/gloss.typ#L144-L146
return `label(key)` in case index==0 to get `@css` instead of `@__gloss:css.0`. However, this would only appear in the autocomplete list, after you have used `@css` at least once.

- Finally, you could add an invisible placeholder label during `init-glossary` just for the purpose of autocompletion, without any functionality. This would always work.



And maybe you could use `"\u{FFFF}__gloss"` as the prefix to push the other "hidden" labels down to the bottom of the autocomplete list @swaits ?

**Comment by swaits** [comment]
I'm interested in this because it's simple and should basically always work:

> Finally, you could add an invisible placeholder label during init-glossary just for the purpose of label-autocompletion, without any functionality. This would always work.

I played around with hidden content a bit, but didn't test it in a Typst-aware auto-completing editor (I mean, I use neovim with a Typst LSP, but I'm not sure this is a fair way to test this compared to OP's experience).

Anyway, is that what you're suggesting here, @eltos?

**Comment by swaits** [comment]
@eltos I created [this branch](https://github.com/swaits/typst-collection/tree/issue-3) to experiment with this. Haven't been able to test it, because I don't have the editor setup OP is using.

Regardless, this approach may confuse the "terms used" and thus taint the output by always listing ever term passed into init. Again, untested, for now.

Here's a link straight to the diff: https://github.com/swaits/typst-collection/commit/f9ca22fe02f151bff207bf83c9b36d7c6152feb4

**Comment by swaits** [comment]
@szymonmasternak can you please describe your editor setup so I can try testing it on my end?

**Comment by szymonmasternak** [comment]
@swaits I used the typst.app editor with the latest version of typst (v0.12.0 i think).

**Comment by swaits** [comment]
Ok thanks. That helps. I should've realized that.

Anyway, I asked for some help in [Discord here](https://discord.com/channels/1054443721975922748/1088371919725793360/1318711794969084015).

**Comment by swaits** [comment]
Saving conversation here for future reference:

![image](https://github.com/user-attachments/assets/b19600d2-8476-4d60-b134-7aca7595aace)

**Comment by eltos** [comment]
> @eltos I created [this branch](https://github.com/swaits/typst-collection/tree/issue-3) to experiment with this. Haven't been able to test it, because I don't have the editor setup OP is using.
> 
> Regardless, this approach may confuse the "terms used" and thus taint the output by always listing ever term passed into init. Again, untested, for now.
> 
> Here's a link straight to the diff: https://github.com/swaits/typst-collection/commit/f9ca22fe02f151bff207bf83c9b36d7c6152feb4

First thought is that using just the hide function will create undesired blank space in the document, as described in the docs:
> The hide function allows you to hide content while the layout still 'sees' it. This is useful to create whitespace that is exactly as large as some content.

I will experiment with it in the next few days. BTW you can always test packages in the web app before submission by simply copying the package files to a project of yours and using the filenames with the import statement instead of the `@preview/...`

**Comment by swaits** [comment]
My test suite seems to show that as long as the hidden content is just labels, it makes no changes to the layout. In other words, all of my tests rendered exactly the same after this change as they did before. Not sure if that'll always hold true or not.

Good call on the way to test in the webapp - didn't realize it could do that.

**Comment by swaits** [comment]
Tested this "hide all the labels at the top of the doc" approach in typst.app and it does not work. First problem with this is you actually need something to label. So, I tried metadata. But metadata cannot be referenced. So, I tried an empty figure, using `place()` to try to avoid layout impact... and nope.

Anyway, when I get some time, I'll take a look at `typst-ide` to try to figure out how to inform it about our labels. Or see if I can get any more ideas from @laurmaedje.

**Comment by eltos** [comment]
> So, I tried metadata. But metadata cannot be referenced.

This is not a problem since for the references in question the show rule anyway calls `__gls`, so it will never come to that point. I have opened a PR which implements this metadata approach: #16
